[package]
name = "day_04"
version = "0.1.0"
authors = ["Žiga Špindler <ziga.spindler@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
